### ISSUE TITLE
Refac / Feat : 보이스봇 채팅

### ISSUE THREAD

**Issue by H0ngJu** [H0ngJu/atti#118]
## 💫 설명

- 기억 회상 대화 부분 기능과 UI를 수정합니다.
![image](https://github.com/H0ngJu/atti/assets/106425326/7aaffbc6-13ad-4efc-99af-74e37f85bc96)

## Todo

- [x]  대화 UI 전면 수정
- [x] 챗봇 대화 api 호출 이슈 해결 (2번 호출하거나, 사용자 말이 입력되지 않는 문제)
- [x] 코드 리팩토링
- [x] 기억 회상 추천 페이지

## 기타
