### ISSUE TITLE
Feat : recollectionData 추가

### ISSUE THREAD

**Issue by jeon-jueun** [H0ngJu/atti#121]
## 💫 설명

- 추억 회상 data 삽입

## Todo

- [x]  1950년대 추억 아이템 2개
- [x]  1960년대 추억 아이템 1개
- [x]  1970년대 추억 아이템 1개

## 기타

-
