### ISSUE TITLE
Chore : 기타 수정사항들 반영

### ISSUE THREAD

**Issue by H0ngJu** [H0ngJu/atti#138]
## 💫 설명

- 영상에 찍을 것들 디테일 수정
- 환자 홈, 기억 갤러리, 알림 페이지를 수정할 예정입니다

## Todo
- [x] 갤러리 버튼이 이미지 가리는 문제 수정
- [x] chat에서 사진 클릭하였을 때 팝업
- [x] 알림 페이지 수정
- [x] 홈 화면 기억 불러오는 코드 수정
- [x] Recollection 대화 수정 (발화자 tts, btn)
- [x] 홈 화면 일과 데이터 수정 (현재 시간과 가까운 일과 중 완료하지 않은 것)
- [x] 리포트 디자인 수정 사항 반영
- [x] 로그아웃 기능
- [x] loggedUser 초기화 문제
- [x] defaultAtti + 날씨에 따라 바뀌도록
- [x] 로그아웃 수정
- [x] 기억 갤러리 tts 추가
- [x] 홈 아래 기억 등록 추가
- [x] newReport 파베 연결

## 기타
