### ISSUE TITLE
Feat : 일과/일정 페이지 재제작

### ISSUE THREAD

**Issue by qkrtnwjd4212** [H0ngJu/atti#193]
## 💫 설명

- 피그마 내 변경된 일과/일정 페이지 플로우에 따라 해당 페이지들을 수정합니다.

## Todo

- [x]  일정/일과 페이지 상단 UI 변경
- [x]  일정 완료 페이지 UI 변경
- [x]  일정 타임라인 UI 변경
- [x]  일과 타임라인 UI 변경
- [x]  완료한 일과 토글 기능 추가
- [x]  일정/일과 완료 플로우
- [x]  일정/일과 삭제 플로우

## 기타

![image](https://github.com/user-attachments/assets/f3e5a733-0efc-4583-b360-ed50f9857b5a)
