### ISSUE TITLE
Feat : 전체화면 알림 UI 수정

### ISSUE THREAD

**Issue by qkrtnwjd4212** [H0ngJu/atti#201]
## 💫 설명

- 피그마 내 변경된 알림 페이지에 따라 전체화면 알림 페이지의 UI를 수정합니다.

## Todo

- [x]  일과 알림 페이지
- [x]  일정 알림 페이지1
- [x]  일정 알림 페이지2
- [x]  푸시알림 로직 수정
- [x]  일정/일과 삭제 시 예약된 푸시알림 삭제 로직 추가  

## 기타

![image](https://github.com/user-attachments/assets/73e7448b-c70a-4a43-9db1-3f3e58df8b09)
