### ISSUE TITLE
Feat : 일정 및 일과 등록 플로우 재제작

### ISSUE THREAD

**Issue by qkrtnwjd4212** [H0ngJu/atti#211]
## 💫 설명

- 피그마 내 변경된 일정/일과 등록 플로우에 따라 해당 페이지들을 수정합니다.
- (+ 기억 등록 플로우 페이지 수정) 

## Todo

- [x]  상단바 UI 수정
- [x]  완료 페이지 UI 수정
- [x]  복약 일과 분리
- [x]  (가능하면) 일과 종료일 로직 추가
- [x]  기타 UI들 수정
- [x]  기억 등록 페이지 UI 수정
- [x]  그 외 인물, 기억 단어 태그 UI 수정, 태그 삭제 로직 추가

## 기타

![image](https://github.com/user-attachments/assets/a5a5716e-b5be-482f-981b-0e4c9486532c)
