### ISSUE TITLE
Feat : 환자홈 기능수정

### ISSUE THREAD

**Issue by jeon-jueun** [H0ngJu/atti#218]
## 💫 설명

- 환자홈 기능수정

## Todo

- [ ]  실제 데이터 수정되도록 손보기
- [ ]  환자 - 보호자 관계 UI 수정
- [ ] 환자 - 보호자 관계 데이터베이스 저장 로직 수정

## 기타

![image](https://github.com/user-attachments/assets/72140a91-cb2a-4416-81bd-c44baabf2f92)
