### ISSUE TITLE
UI : 회원가입 ui 작업

### ISSUE THREAD

**Issue by jeon-jueun** [H0ngJu/atti#4]
<aside>
## 💫 설명

- 회원가입 UI, 파베연결

## Todo

- [x]  회원가입 UI 그리기
- [x]  회원가입 firebase 연결
- [x] auth 적용해서 유저 생성

## 기타

- 
</aside>
