### ISSUE TITLE
Feat : Gemini API 연결 

### ISSUE THREAD

**Issue by qkrtnwjd4212** [H0ngJu/atti#92]
## 💫 설명

- OpenAI api를 gemini api로 변경

## Todo

- [x]  api 연결
- [x]  사용자 음성 여러 번 전송되는 오류 해결
- [x]  아띠 음성만 들리도록 수정
- [x]  멀티모달로 변경, 기억 이미지 전송
- [x]  대화 종료 후 사용자 감정 분석
- [x]  위험 단어 분석
- [x]  Stream 적용
