### ISSUE TITLE
Refac : 환자 홈 화면 전면 수정

### ISSUE THREAD

**Issue by H0ngJu** [H0ngJu/atti#97]
## 💫 설명

- 홈 화면 수정과 리팩토링
![image](https://github.com/H0ngJu/atti/assets/106425326/886a9f36-3813-4ca9-90c9-2fb80cea4be1)

## Todo

- [x] 메인 UI 디자인 수정
- [x] 파베 연동 리팩토링
- [x] 내 기억 -> 캘린더 변경

## 기타
